CACHE MANIFEST
# V. 0.1 <?php echo(date('Y-m-d H:i')); ?>
index.html
reglement
medias/styles/css/styles.css
medias/scripts/main.min.js
medias/vendor/jquery/dist/jquery.min.js
medias/fonts/Frutiger45Light.eot
medias/fonts/Frutiger45Light.otf
medias/fonts/Frutiger45Light.svg
medias/fonts/Frutiger45Light.ttf
medias/fonts/Frutiger45Light.woff
medias/fonts/Frutiger55Roman.eot
medias/fonts/Frutiger55Roman.otf
medias/fonts/Frutiger55Roman.svg
medias/fonts/Frutiger55Roman.ttf
medias/fonts/Frutiger55Roman.woff
medias/fonts/Frutiger65Bold.eot
medias/fonts/Frutiger65Bold.otf
medias/fonts/Frutiger65Bold.svg
medias/fonts/Frutiger65Bold.ttf
medias/fonts/Frutiger65Bold.woff
medias/images/favicon.png
medias/images/icon.png
medias/images/nikon.svg
medias/images/csv-file.svg
medias/images/accueil.svg
medias/images/envoyer.svg
medias/images/nikon-background-1.jpg
medias/images/nikon-background-2.jpg
medias/images/nikon-background-3.jpg
medias/images/offre-produits-1.png
medias/images/offre-produits-2.png
medias/images/offre-promotionnelle-background.jpg
medias/images/lot-1.jpg
medias/images/lot-2.jpg
medias/images/lot-3.png
<?php
foreach($images as $image)
{
    echo('medias/images/items/' . $image . PHP_EOL);
}
?>

NETWORK:
*