<?php
echo template(
    'partials/common/header.phtml',
    [
        'title' => 'Enchères',
    ]
);
?>
<div class="container">
<div id="startGame">
    <div class="row mt20 mb10">
        <div class="col-md-12">
            <p>Bienvenue chez Mercier, votre commisseur priseur. Grâce à un partenariat avec Gogol Inc., nous vous proposons des enchères rapides, sécurisées et intéressantes via cette interface digitale.</p>
            <p>Les sessions d'enchères se déroulent en 3 phases durant lesquelles 10 lots vous seront proposés. Chaque manche regroupe des objets de valeurs similaires, les meilleurs lots étant présentés lors de la dernière manche.</p>
            <p>Vous serez immédiatement débité du montant des enchères remportées durant une manche.</p>
            <p>À la fin de chaque manche, les lots que vous avez remportés sont automatiquement revendus à leur valeur marchande (prix de revente) : vous touchez alors la différence avec votre prix d'achat.</p>
            <p><strong>Nous vous souhaitons de bonnes enchères !</strong></p>
        </div>
    </div>
    <div class="row">
        <col-md-6>
            <h2>Mon profil</h2>
            <p>1. Identifiez-vous :</p>
            <div class="mt10 mb20 textCenter">
                <?php foreach($joueurs as $joueur): ?>
                <div class="joueurselector" data-id="<?php echo($joueur->getId()); ?>">
                    <span class="name"><?php echo($joueur->getName()); ?></span>
                </div>
                <?php endforeach; ?>
            </div>
        </col-md-6>
        <col-md-6>
            <h2>Séance d'enchères</h2>
            <p>2. Créer une session ou choisissez celle que vous souhaitez rejoindre :</p>
            <?php if(isset($error)): ?>
            <p class="error"><?php echo($error); ?></p>
            <?php endif; ?>
            <div class="row mt20">
                <div class="col-md-6 textCenter">Rejoindre la session #
                    <form action="<?php echo(di('router')->pathFor('ENCHERES')); ?>" name="join" method="post">
                        <input type="hidden" name="joueurId" value="0"/>
                        <input type="number" name="partieId" />
                        <span id="joinSession" class="button disabled">Rejoindre</span>
                    </form>
                </div>
                <div class="col-md-6 textCenter">
                    <form action="<?php echo(di('router')->pathFor('ENCHERES')); ?>" name="join" method="post">
                        <input type="hidden" name="joueurId" value="0"/>
                        <span id="createSession" class="button disabled">Créer une session</span>
                    </form>
                </div>
            </div>
        </col-md-6>
    </div>
</div>

<script type="text/javascript" src="<?php echo baseUrl('medias/scripts/start.min.js'); ?>"></script>
<?php echo template('partials/common/footer.phtml'); ?>